name: premake5-ubuntu-gmake

on:
  workflow_dispatch:
  push:
    paths:
      - 'project-*/**'
      - .github/workflows/premake5-ubuntu-gmake.yml
  pull_request:
    paths:
      - 'project-*/**'
      - .github/workflows/premake5-ubuntu-gmake.yml

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action: [gmake, gmake2]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: checkout premake5
      uses: actions/checkout@v2
      with:
          repository: T-rvw/premake-core
          path: premake-build
    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build

    - name: test projects
      run: PATH=$PATH:. ./test_projects.sh premake5 ${{ matrix.action }}
